In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [6]:


import numpy as np

print(np.__version__)

1.26.4


In [12]:
#task2

arr_1d=np.array([1,2,3,4,5])
arr_2d=np.zeros((3,3))
arr_3x3=np.ones((3,3))
arr_random=np.random.random((4,4))

print(f"1D array:\n {arr_1d}\n")
print(f"2D Array of Zeros:\n {arr_2d}\n")
print(f"3x3 Array of Ones:\n {arr_3x3}\n")
print(f"Random 4x4 Array:\n {arr_random}")

1D array:
 [1 2 3 4 5]

2D Array of Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

3x3 Array of Ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Random 4x4 Array:
 [[0.34040201 0.1122435  0.25530618 0.22726736]
 [0.67104973 0.80062963 0.78042014 0.78130636]
 [0.55195436 0.43870786 0.76385094 0.5593683 ]
 [0.84400314 0.13281477 0.81262726 0.62319782]]


In [18]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])

print(f"Addition : \n {x+y} \n")
print(f"Multiplication : \n {x*y} \n")
print(f"Matrix Multiplication : \n {x@y} \n")

Addition : 
 [[ 6  8]
 [10 12]] 

Multiplication : 
 [[ 5 12]
 [21 32]] 

Matrix Multiplication : 
 [[19 22]
 [43 50]] 



In [23]:
mat= np.random.randint(0,100,(5,5))

mean=np.mean(mat)
std_dev=np.std(mat)

normalize=(mat-mean)/std_dev

print(f"Matrix 5x5 : \n {mat}\n")
print(f"Mean : {mean} \n")
print(f"Standard Deviation : {std_dev}\n")
print(f"Normalized Matrix :\n {normalize}")

Matrix 5x5 : 
 [[90  6 75 18 95]
 [44 83 96 47 26]
 [89 15 96 91 29]
 [ 5  5 74  2 81]
 [16 95 80 41 78]]

Mean : 55.08 

Standard Deviation : 34.763106880714794

Normalized Matrix :
 [[ 1.00451321 -1.41184159  0.57302128 -1.06664805  1.14834385]
 [-0.3187287   0.80315031  1.17710998 -0.23243032 -0.83651902]
 [ 0.97574708 -1.15294643  1.17710998  1.03327934 -0.75022063]
 [-1.44060772 -1.44060772  0.54425515 -1.5269061   0.74561805]
 [-1.1241803   1.14834385  0.71685192 -0.40502709  0.65931967]]


In [27]:
import time


python_list = list(range(1, 1000001))
numpy_array = np.arange(1, 1000001)

start_time = time.time()
sum_python_list = sum(python_list)
python_time = time.time() - start_time

start_time = time.time()
sum_numpy_array = np.sum(numpy_array)
numpy_time = time.time() - start_time

print(f"Sum of Python List: {sum_python_list}, Time Taken: {python_time:.6f} seconds")
print(f"Sum of NumPy Array: {sum_numpy_array}, Time Taken: {numpy_time:.6f} seconds")

Sum of Python List: 500000500000, Time Taken: 0.019226 seconds
Sum of NumPy Array: 1784293664, Time Taken: 0.000000 seconds
